[theme]
primaryColor = "#4A90E2"             # Azul suave para botones
backgroundColor = "#E0E5EC"          # Gris claro azulado (fondo general)
secondaryBackgroundColor = "#F0F3F7" # Paneles un poco más claros
textColor = "#2C3E50"                # Gris oscuro para el texto
font = "sans serif"
